---

- name: include vars
  include_vars:
    dir: vars

- name: Find old outputs
  find:
    paths: "{{ ['/tmp', output_directory | default('/tmp/.nothing') | dirname] | unique }}"
    file_type: any
    patterns:
      - 'ansible*_packer_build_*'
      - 'packer-log*'
      - 'packer*.iso'
      - 'packer_to_cdrom*'
      - "{{ output_directory | default('/tmp/.nothing') | basename }}"
    recurse: false
  register: old_outputs
  when: do_cleanup | bool

- name: Remove old outputs
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ old_outputs.files }}"
  loop_control:
    label: "{{ item.path }}"
  when: do_cleanup | bool

- name: Create temporary work directory
  tempfile:
    state: directory
    suffix: _packer_build_{{ packer_builder }}_{{ target_fullname }}
  register: tempdir

- name: Create Packer build file
  template:
    src: templates/build-{{ packer_builder }}.json.j2
    dest: "{{ tempdir.path }}/build.json"

- name: Create installer configuration file
  template:
    src: templates/cfg-{{ target_config }}.j2
    dest: "{{ tempdir.path }}/inst.cfg"

- name: Create Packer provisioner script
  template:
    src: templates/{{ sysprep_script }}.j2
    dest: "{{ tempdir.path }}/inst-sysprep"

- name: Run Packer to build target image
  command:
    cmd: "{{ packer_binary }} build -color=false {{ '-force' if use_force | bool else '' }} build.json"
    chdir: "{{ tempdir.path }}"
  environment:
    CHECKPOINT_DISABLE: 1
  register: packer_result
  failed_when: "'successful build' not in packer_result.stdout"

- name: Display Packer command output
  debug:
    var: packer_result.stdout

- name: Remove temporary work directory
  file:
    path: "{{ tempdir.path }}"
    state: absent
  when: do_cleanup | bool
